media:
  input: public
  output: /
content:
  - name: news
    label: News
    type: collection
    path: content/news
    view:
      fields: [ title, draft, date ]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: author, label: Author, type: string }
      - { name: canonicalUrl, label: Canonical Url, type: string }
      - { name: draft, label: Draft, type: boolean }
      - { name: body, label: Body, type: rich-text }
  - name: about
    label: About page
    type: file
    path: content/about.md
    fields:
      - { name: title, label: Title, type: string }
      - { name: description, label: Description, type: text }
      - { name: body, label: Body, type: rich-text, options: { input: public/assets, output: /assets } }