media: static/images
content:
  - name: news
    label: News
    type: collection
    path: content/news
    view:
      fields: [ title, draft, date ]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: author, label: Author, type: string }
      - { name: canonicalUrl, label: Canonical Url, type: string }
      - { name: draft, label: Draft, type: boolean }
      - { name: body, label: Body, type: rich-text }
  - name: careers
    label: Job Requests
    type: collection
    path: content/careers
    view:
      fields: [ title, draft, date ]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: position, label: Position Type, type: select, options: {[ tech, News, Sports]}}
      - { name: post_date, label: Posted Date, type: date, required: true }
      - { name: base_salary, label: Base Salary, type: number }
      - { name: maximum_salary, label: Max Salary, type: number }
      - { name: draft, label: Draft, type: boolean }
      - { name: body, label: Body, type: rich-text }      
  - name: about
    label: About page
    type: file
    path: content/about.md
    fields:
      - { name: title, label: Title, type: string }
      - { name: description, label: Description, type: text }
      - { name: body, label: Body, type: rich-text, options: { input: public/assets, output: /assets } }
  - name: state-based-marketplace
    label: SBM Page
    type: file
    path: content/state-based-marketplace.md
    fields:
      - { name: title, label: Title, type: string }
      - { name: description, label: Description, type: text }
      - { name: body, label: Body, type: rich-text, options: { input: public/assets, output: /assets } }
  - name: careers
    label: Careers Page
    type: file
    path: content/careers/_index.md
    fields:
      - { name: title, label: Title, type: string }
      - { name: description, label: Description, type: text }
      - { name: body, label: Body, type: rich-text, options: { input: public/assets, output: /assets } }      